export const helpMessages = {
      en: {
        help_title: "Help Using SWAT+ Editor",
        help_desc: "SWAT+ Editor is an interface to SWAT+ that allows users to import a project from GIS, modify SWAT+ input, write the text files, and run the model.",
        help_note_part1: "*Note: While you may change your version of SWAT+ used in the editor, we recommend only doing so with caution and knowledge of model changes between the versions. If there are input and output file changes, you may run into errors or inaccurate results. To change your model version, go to the ",
        help_note_part2: " tab and select one of the built-in versions from the drop down menu, or click the gear icon to get advanced instructions.",
        about_title: "About SWAT+",
        about_desc: "The Soil and Water Assessment Tool Plus (SWAT+) is a public domain model jointly developed by the USDA Agricultural Research Service (USDA-ARS) and Texas A&M AgriLife Research, part of The Texas A&M University System. SWAT+ is a small watershed to river basin-scale model to simulate the quality and quantity of surface and ground water and predict the environmental impact of land use, land management practices, and climate change. SWAT is widely used in assessing soil erosion prevention and control, non-point source pollution control and regional management in watersheds.",
        disclaimer_title: "Disclaimer",
        disclaimer_text: "The information contained within this software is offered as a public service. It is the responsibility of the user to verify the accuracy, completeness, timeliness, quality, or suitability for a particular use of the information/ software provided. Neither Grassland, Soil & Water Research Laboratory (GSWRL), Blackland Research Center (BRC), nor Texas A&M AgriLife Research (TALR) make any claims, guarantees, or warranties about the accuracy, completeness, timeliness, quality, or suitability for a particular use of this software. GSWRL, BRC, and TALR disclaim any and all liability for any claims or damages that may result from providing the website or the information/ software contained within. The user of this software assumes all liability and waives any and all claims or causes of action against GSWRL, BRC, and TALR for all uses of and reliance on the information/ software. GSWRL, BRC, and TALR do not endorse any commercial entities, products, consultants, or documentation that may be referenced in this software. The information contained within this software is provided for general information purposes, and is not intended to be a solicitation or an offer to sell in connection with any product or service. Any reference to commercial entities, products, or consultants is for information purposes only.",
        
        help:"Help"
      },

      id: {
        help_title: "Bantuan Menggunakan SWAT+ Editor",
        help_desc: "SWAT+ Editor adalah antarmuka untuk SWAT+ yang memungkinkan pengguna mengimpor proyek dari GIS, memodifikasi input SWAT+, menulis file teks, dan menjalankan model.",
        help_note_part1: "*Catatan: Meskipun Anda dapat mengubah versi SWAT+ yang digunakan di editor, kami sarankan untuk melakukannya dengan hati-hati dan pengetahuan tentang perubahan model antar versi. Jika terdapat perubahan file input dan output, Anda mungkin mengalami error atau hasil yang tidak akurat. Untuk mengubah versi model Anda, buka tab ",
        help_note_part2: " dan pilih salah satu versi bawaan dari menu drop-down, atau klik ikon roda gigi untuk mendapatkan petunjuk tingkat lanjut.",
        about_title: "Tentang SWAT+",
        about_desc: "Soil and Water Assessment Tool Plus (SWAT+) adalah model domain publik yang dikembangkan bersama oleh USDA Agricultural Research Service (USDA-ARS) dan Texas A&M AgriLife Research, bagian dari The Texas A&M University System. SWAT+ adalah model skala daerah aliran sungai kecil hingga cekungan sungai untuk mensimulasikan kualitas dan kuantitas air permukaan dan tanah serta memprediksi dampak lingkungan dari penggunaan lahan, praktik pengelolaan lahan, dan perubahan iklim. SWAT digunakan secara luas dalam menilai pencegahan dan pengendalian erosi tanah, pengendalian polusi sumber non-titik, dan pengelolaan regional di daerah aliran sungai.",
        disclaimer_title: "Pernyataan Penyangkalan (Disclaimer)",
        disclaimer_text: "Informasi yang terkandung dalam perangkat lunak ini ditawarkan sebagai layanan publik. Merupakan tanggung jawab pengguna untuk memverifikasi keakuratan, kelengkapan, ketepatan waktu, kualitas, atau kesesuaian untuk penggunaan tertentu dari informasi/perangkat lunak yang disediakan. Baik Grassland, Soil & Water Research Laboratory (GSWRL), Blackland Research Center (BRC), maupun Texas A&M AgriLife Research (TALR) tidak membuat klaim, jaminan, atau garansi apa pun mengenai keakuratan, kelengkapan, ketepatan waktu, kualitas, atau kesesuaian untuk penggunaan tertentu dari perangkat lunak ini. GSWRL, BRC, dan TALR menyangkal semua tanggung jawab atas klaim atau kerusakan apa pun yang mungkin timbul dari penyediaan situs web atau informasi/perangkat lunak yang terkandung di dalamnya. Pengguna perangkat lunak ini menanggung semua kewajiban dan melepaskan semua klaim atau penyebab tindakan terhadap GSWRL, BRC, dan TALR untuk semua penggunaan dan ketergantungan pada informasi/perangkat lunak tersebut. GSWRL, BRC, dan TALR tidak mendukung entitas komersial, produk, konsultan, atau dokumentasi apa pun yang mungkin direferensikan dalam perangkat lunak ini. Informasi yang terkandung dalam perangkat lunak ini disediakan untuk tujuan informasi umum, dan tidak dimaksudkan sebagai ajakan atau penawaran untuk menjual sehubungan dengan produk atau layanan apa pun. Referensi apa pun ke entitas komersial, produk, atau konsultan hanya untuk tujuan informasi.",

        help: "Bantuan"



      },
        nl: {
        help_title: "Hulp bij het gebruik van SWAT+ Editor",
        help_desc: "SWAT+ Editor is een interface voor SWAT+ waarmee gebruikers een project vanuit GIS kunnen importeren, SWAT+ invoer kunnen wijzigen, tekstbestanden kunnen schrijven en het model kunnen uitvoeren.",
        help_note_part1: "*Opmerking: Hoewel u de versie van SWAT+ die in de editor wordt gebruikt kunt wijzigen, raden we aan dit alleen te doen met voorzichtigheid en kennis van modelwijzigingen tussen de versies. Als er wijzigingen zijn in invoer- en uitvoerbestanden, kunt u tegen fouten of onnauwkeurige resultaten aanlopen. Om uw modelversie te wijzigen, gaat u naar het tabblad ",
        help_note_part2: " en selecteert u een van de ingebouwde versies in het vervolgkeuzemenu, of klikt u op het tandwielpictogram voor geavanceerde instructies.",
        about_title: "Over SWAT+",
        about_desc: "De Soil and Water Assessment Tool Plus (SWAT+) is een publiek domein-model dat gezamenlijk is ontwikkeld door de USDA Agricultural Research Service (USDA-ARS) en Texas A&M AgriLife Research, onderdeel van The Texas A&M University System. SWAT+ is een model op schaal van kleine stroomgebieden tot rivierbekkens om de kwaliteit en kwantiteit van oppervlakte- en grondwater te simuleren en de milieu-impact van landgebruik, landbeheerpraktijken en klimaatverandering te voorspellen. SWAT wordt veel gebruikt bij het beoordelen van preventie en beheersing van bodemerosie, beheersing van diffuse verontreiniging en regionaal beheer in stroomgebieden.",
        disclaimer_title: "Disclaimer",
        disclaimer_text: "De informatie in deze software wordt aangeboden als een publieke dienst. Het is de verantwoordelijkheid van de gebruiker om de nauwkeurigheid, volledigheid, tijdigheid, kwaliteit of geschiktheid voor een bepaald gebruik van de verstrekte informatie/software te verifiëren. Noch het Grassland, Soil & Water Research Laboratory (GSWRL), Blackland Research Center (BRC), noch Texas A&M AgriLife Research (TALR) doen enige claims, garanties of waarborgen over de nauwkeurigheid, volledigheid, tijdigheid, kwaliteit of geschiktheid voor een bepaald gebruik van deze software. GSWRL, BRC en TALR wijzen elke aansprakelijkheid af voor eventuele claims of schade die kunnen voortvloeien uit het verstrekken van de website of de informatie/software die daarin is opgenomen. De gebruiker van deze software aanvaardt alle aansprakelijkheid en ziet af van alle claims of rechtsvorderingen tegen GSWRL, BRC en TALR voor elk gebruik van en vertrouwen op de informatie/software. GSWRL, BRC en TALR onderschrijven geen commerciële entiteiten, producten, consultants of documentatie waarnaar in deze software wordt verwezen. De informatie in deze software wordt verstrekt voor algemene informatiedoeleinden en is niet bedoeld als uitnodiging of aanbod tot verkoop in verband met enig product of dienst. Elke verwijzing naar commerciële entiteiten, producten of consultants is uitsluitend bedoeld voor informatiedoeleinden.",

        help: "Hulp"



    },

    ru: {
        help_title: "Помощь по использованию SWAT+ Editor",
        help_desc: "SWAT+ Editor — это интерфейс для SWAT+, который позволяет пользователям импортировать проект из GIS, изменять входные данные SWAT+, записывать текстовые файлы и запускать модель.",
        help_note_part1: "*Примечание: Хотя вы можете изменить версию SWAT+, используемую в редакторе, мы рекомендуем делать это только с осторожностью и знанием изменений модели между версиями. Если произошли изменения во входных и выходных файлах, вы можете столкнуться с ошибками или неточными результатами. Чтобы изменить версию модели, перейдите на вкладку ",
        help_note_part2: " и выберите одну из встроенных версий из выпадающего меню или нажмите на значок шестеренки для получения расширенных инструкций.",
        about_title: "О программе SWAT+",
        about_desc: "Soil and Water Assessment Tool Plus (SWAT+) — это общедоступная модель, совместно разработанная Сельскохозяйственной исследовательской службой Министерства сельского хозяйства США (USDA-ARS) и Texas A&M AgriLife Research, входящей в систему Техасского университета A&M. SWAT+ — это модель масштаба от малого водораздела до речного бассейна, предназначенная для моделирования качества и количества поверхностных и грунтовых вод и прогнозирования воздействия землепользования, методов управления земельными ресурсами и изменения климата на окружающую среду. SWAT широко используется при оценке предотвращения и контроля эрозии почв, борьбе с неточечными источниками загрязнения и региональном управлении в водоразделах.",
        disclaimer_title: "Отказ от ответственности",
        disclaimer_text: "Информация, содержащаяся в этом программном обеспечении, предлагается в качестве государственной услуги. Пользователь несет ответственность за проверку точности, полноты, своевременности, качества или пригодности для конкретного использования предоставленной информации/программного обеспечения. Ни Лаборатория исследований пастбищ, почв и воды (GSWRL), ни Исследовательский центр Blackland (BRC), ни Texas A&M AgriLife Research (TALR) не делают никаких заявлений, гарантий или заверений относительно точности, полноты, своевременности, качества или пригодности для конкретного использования этого программного обеспечения. GSWRL, BRC и TALR отказываются от любой ответственности за любые претензии или ущерб, которые могут возникнуть в результате предоставления веб-сайта или содержащейся в нем информации/программного обеспечения. Пользователь этого программного обеспечения принимает на себя всю ответственность и отказывается от любых претензий или исков против GSWRL, BRC и TALR за все виды использования и доверия к информации/программному обеспечению. GSWRL, BRC и TALR не поддерживают никакие коммерческие организации, продукты, консультантов или документацию, на которые могут быть ссылки в этом программном обеспечении. Информация, содержащаяся в этом программном обеспечении, предоставляется для общих информационных целей и не предназначена для использования в качестве оферты или предложения о продаже в связи с каким-либо продуктом или услугой. Любая ссылка на коммерческие организации, продукты или консультантов предназначена только для информационных целей.",

        help: "Помощь"
    }
};