from whitebox.whitebox_tools import WhiteboxTools
wbt = WhiteboxTools()

# Mendapatkan semua tools
tools = wbt.list_tools()

# Mencari yang mengandung kata 'fill'
for tool in tools:
    print(tool)
        
        
        
        
# --- Mencari perintah terkait flow ---
# average_flowpath_slope
# average_upslope_flowpath_length
# d8_flow_accumulation
# d8_pointer
# d_inf_flow_accumulation
# d_inf_pointer
# downslope_flowpath_length
# fd8_flow_accumulation
# fd8_pointer
# find_no_flow_cells
# find_parallel_flow
# flow_accumulation_full_workflow
# flow_length_diff
# longest_flowpath
# md_inf_flow_accumulation
# max_upslope_flowpath_length
# num_inflowing_neighbours
# qin_flow_accumulation
# quinn_flow_accumulation
# rho8_flow_accumulation
# rho8_pointer
# trace_downslope_flowpaths


# all command
# absolute_value
# adaptive_filter
# add
# add_point_coordinates_to_table
# aggregate_raster
# and
# anova
# arc_cos
# arc_sin
# arc_tan
# arcosh
# arsinh
# artanh
# ascii_to_las
# aspect
# atan2
# attribute_correlation
# attribute_correlation_neighbourhood_analysis
# attribute_histogram
# attribute_scattergram
# average_flowpath_slope
# average_normal_vector_angular_deviation
# average_overlay
# average_upslope_flowpath_length
# balance_contrast_enhancement
# basins
# bilateral_filter
# block_maximum_gridding
# block_minimum_gridding
# boundary_shape_complexity
# breach_depressions
# breach_depressions_least_cost
# breach_single_cell_pits
# buffer_raster
# burn_streams_at_roads
# ceil
# centroid
# centroid_vector
# change_vector_analysis
# circular_variance_of_aspect
# classify_buildings_in_lidar
# classify_overlap_points
# clean_vector
# clip
# clip_lidar_to_polygon
# clip_raster_to_polygon
# closing
# clump
# compactness_ratio
# conditional_evaluation
# conditioned_latin_hypercube
# conservative_smoothing_filter
# construct_vector_tin
# contours_from_points
# contours_from_raster
# convergence_index
# convert_nodata_to_zero
# convert_raster_format
# corner_detection
# correct_stream_vector_direction
# correct_vignetting
# cos
# cosh
# cost_allocation
# cost_distance
# cost_pathway
# count_if
# create_colour_composite
# create_hexagonal_vector_grid
# create_plane
# create_rectangular_vector_grid
# crispness_index
# cross_tabulation
# csv_points_to_vector
# cumulative_distribution
# d8_flow_accumulation
# d8_mass_flux
# d8_pointer
# d_inf_flow_accumulation
# d_inf_mass_flux
# d_inf_pointer
# decrement
# depth_in_sink
# dev_from_mean_elev
# deviation_from_regional_direction
# diff_from_mean_elev
# diff_of_gaussian_filter
# difference
# direct_decorrelation_stretch
# directional_relief
# dissolve
# distance_to_outlet
# diversity_filter
# divide
# downslope_distance_to_stream
# downslope_flowpath_length
# downslope_index
# edge_contamination
# edge_density
# edge_preserving_mean_filter
# edge_proportion
# elev_above_pit
# elev_percentile
# elev_relative_to_min_max
# elev_relative_to_watershed_min_max
# elevation_above_stream
# elevation_above_stream_euclidean
# eliminate_coincident_points
# elongation_ratio
# embankment_mapping
# emboss_filter
# equal_to
# erase
# erase_polygon_from_lidar
# erase_polygon_from_raster
# euclidean_allocation
# euclidean_distance
# exp
# exp2
# export_table_to_csv
# exposure_towards_wind_flux
# extend_vector_lines
# extract_by_attribute
# extract_nodes
# extract_raster_values_at_points
# extract_streams
# extract_valleys
# fd8_flow_accumulation
# fd8_pointer
# farthest_channel_head
# fast_almost_gaussian_filter
# feature_preserving_smoothing
# fetch_analysis
# fill_burn
# fill_depressions
# fill_depressions_planchon_and_darboux
# fill_depressions_wang_and_liu
# fill_missing_data
# fill_single_cell_pits
# filter_lidar_classes
# filter_lidar_scan_angles
# filter_raster_features_by_area
# find_flightline_edge_points
# find_lowest_or_highest_points
# find_main_stem
# find_no_flow_cells
# find_parallel_flow
# find_patch_or_class_edge_cells
# find_ridges
# flatten_lakes
# flightline_overlap
# flip_image
# flood_order
# floor
# flow_accumulation_full_workflow
# flow_length_diff
# gamma_correction
# gaussian_contrast_stretch
# gaussian_curvature
# gaussian_filter
# gaussian_scale_space
# geomorphons
# greater_than
# hack_stream_order
# heat_map
# height_above_ground
# high_pass_bilateral_filter
# high_pass_filter
# high_pass_median_filter
# highest_position
# hillshade
# hillslopes
# histogram_equalization
# histogram_matching
# histogram_matching_two_images
# hole_proportion
# horizon_angle
# horton_stream_order
# hypsometric_analysis
# hypsometrically_tinted_hillshade
# idw_interpolation
# ihs_to_rgb
# image_autocorrelation
# image_correlation
# image_correlation_neighbourhood_analysis
# image_regression
# image_stack_profile
# impoundment_size_index
# in_place_add
# in_place_divide
# in_place_multiply
# in_place_subtract
# increment
# individual_tree_detection
# insert_dams
# install_wb_extension
# integer_division
# integral_image
# intersect
# is_no_data
# isobasins
# jenson_snap_pour_points
# join_tables
# k_means_clustering
# k_nearest_mean_filter
# kappa_index
# ks_test_for_normality
# laplacian_filter
# laplacian_of_gaussian_filter
# las_to_ascii
# las_to_multipoint_shapefile
# las_to_shapefile
# las_to_zlidar
# launch_wb_runner
# layer_footprint
# lee_sigma_filter
# length_of_upstream_channels
# less_than
# lidar_block_maximum
# lidar_block_minimum
# lidar_classify_subset
# lidar_colourize
# lidar_digital_surface_model
# lidar_elevation_slice
# lidar_ground_point_filter
# lidar_hex_binning
# lidar_hillshade
# lidar_histogram
# lidar_idw_interpolation
# lidar_info
# lidar_join
# lidar_kappa_index
# lidar_nearest_neighbour_gridding
# lidar_point_density
# lidar_point_stats
# lidar_ransac_planes
# lidar_rbf_interpolation
# lidar_remove_duplicates
# lidar_remove_outliers
# lidar_rooftop_analysis
# lidar_segmentation
# lidar_segmentation_based_filter
# lidar_shift
# lidar_tin_gridding
# lidar_thin
# lidar_thin_high_density
# lidar_tile
# lidar_tile_footprint
# lidar_tophat_transform
# line_detection_filter
# line_intersections
# line_thinning
# linearity_index
# lines_to_polygons
# list_unique_values
# list_unique_values_raster
# ln
# local_quadratic_regression
# log10
# log2
# long_profile
# long_profile_from_points
# longest_flowpath
# lowest_position
# md_inf_flow_accumulation
# majority_filter
# map_off_terrain_objects
# max
# max_absolute_overlay
# max_anisotropy_dev
# max_anisotropy_dev_signature
# max_branch_length
# max_difference_from_mean
# max_downslope_elev_change
# max_elev_dev_signature
# max_elevation_deviation
# max_overlay
# max_upslope_elev_change
# max_upslope_flowpath_length
# max_upslope_value
# maximal_curvature
# maximum_filter
# mean_curvature
# mean_filter
# median_filter
# medoid
# merge_line_segments
# merge_table_with_csv
# merge_vectors
# min
# min_absolute_overlay
# min_downslope_elev_change
# min_max_contrast_stretch
# min_overlay
# minimal_curvature
# minimum_bounding_box
# minimum_bounding_circle
# minimum_bounding_envelope
# minimum_convex_hull
# minimum_filter
# modified_k_means_clustering
# modify_no_data_value
# modulo
# mosaic
# mosaic_with_feathering
# multi_part_to_single_part
# multidirectional_hillshade
# multiply
# multiply_overlay
# multiscale_elevation_percentile
# multiscale_roughness
# multiscale_roughness_signature
# multiscale_std_dev_normals
# multiscale_std_dev_normals_signature
# multiscale_topographic_position_image
# narrowness_index
# natural_neighbour_interpolation
# nearest_neighbour_gridding
# negate
# new_raster_from_base
# normal_vectors
# normalize_lidar
# normalized_difference_index
# not
# not_equal_to
# num_downslope_neighbours
# num_inflowing_neighbours
# num_upslope_neighbours
# olympic_filter
# opening
# or
# otsu_thresholding
# paired_sample_t_test
# panchromatic_sharpening
# patch_orientation
# pennock_landform_class
# percent_elev_range
# percent_equal_to
# percent_greater_than
# percent_less_than
# percentage_contrast_stretch
# percentile_filter
# perimeter_area_ratio
# pick_from_list
# plan_curvature
# polygon_area
# polygon_long_axis
# polygon_perimeter
# polygon_short_axis
# polygonize
# polygons_to_lines
# power
# prewitt_filter
# principal_component_analysis
# print_geo_tiff_tags
# profile
# profile_curvature
# qin_flow_accumulation
# quantiles
# quinn_flow_accumulation
# radial_basis_function_interpolation
# radius_of_gyration
# raise_walls
# random_field
# random_sample
# range_filter
# raster_area
# raster_calculator
# raster_cell_assignment
# raster_histogram
# raster_perimeter
# raster_streams_to_vector
# raster_summary_stats
# raster_to_vector_lines
# raster_to_vector_points
# raster_to_vector_polygons
# rasterize_streams
# reciprocal
# reclass
# reclass_equal_interval
# reclass_from_file
# reinitialize_attribute_table
# related_circumscribing_circle
# relative_aspect
# relative_topographic_position
# remove_off_terrain_objects
# remove_polygon_holes
# remove_short_streams
# remove_spurs
# repair_stream_vector_topology
# resample
# rescale_value_range
# rgb_to_ihs
# rho8_flow_accumulation
# rho8_pointer
# roberts_cross_filter
# root_mean_square_error
# round
# ruggedness_index
# scharr_filter
# sediment_transport_index
# select_tiles_by_polygon
# set_nodata_value
# shape_complexity_index
# shape_complexity_index_raster
# shreve_stream_magnitude
# sigmoidal_contrast_stretch
# sin
# single_part_to_multi_part
# sinh
# sink
# slope
# slope_vs_elevation_plot
# smooth_vectors
# snap_pour_points
# sobel_filter
# spherical_std_dev_of_normals
# split_colour_composite
# split_vector_lines
# split_with_lines
# square
# square_root
# standard_deviation_contrast_stretch
# standard_deviation_filter
# standard_deviation_of_slope
# stochastic_depression_analysis
# strahler_order_basins
# strahler_stream_order
# stream_link_class
# stream_link_identifier
# stream_link_length
# stream_link_slope
# stream_power_index
# stream_slope_continuous
# subbasins
# subtract
# sum_overlay
# surface_area_ratio
# symmetrical_difference
# tin_gridding
# tan
# tangential_curvature
# tanh
# thicken_raster_line
# time_in_daylight
# to_degrees
# to_radians
# tophat_transform
# topographic_hachures
# topological_stream_order
# total_curvature
# total_filter
# trace_downslope_flowpaths
# travelling_salesman_problem
# trend_surface
# trend_surface_vector_points
# tributary_identifier
# truncate
# turning_bands_simulation
# two_sample_ks_test
# union
# unnest_basins
# unsharp_masking
# update_nodata_cells
# upslope_depression_storage
# user_defined_weights_filter
# vector_hex_binning
# vector_lines_to_raster
# vector_points_to_raster
# vector_polygons_to_raster
# vector_stream_network_analysis
# viewshed
# visibility_index
# voronoi_diagram
# watershed
# weighted_overlay
# weighted_sum
# wetness_index
# wilcoxon_signed_rank_test
# write_function_memory_insertion
# xor
# z_scores
# zlidar_to_las
# zonal_statistics